language: python
python: '2.7'
env:
  - DJANGO_VERSION="django>=1.5,<1.5.99"
  - DJANGO_VERSION="django>=1.6,<1.6.99"
install:
  - 'pip install $DJANGO_VERSION'
  - 'pip install -q -e . --use-mirrors'
script:
  - 'cd test_project'
  - 'python manage.py test mezzanine_agenda'
